#!/usr/bin/env python
import sys
import os

if len(sys.argv) != 4:
    print "error: need 3 args"
    exit()

high = max(int(sys.argv[1]), int(sys.argv[2]))
low  = min(int(sys.argv[1]), int(sys.argv[2])) - 1

for i in range(high, low, -1):

    cmd = './wefunk_dl ' + str(i)
    print cmd
    os.system(cmd)

    cmd = "mv *" + str(i) + '* ' + sys.argv[3]
    print cmd
    os.system(cmd)

